# Generated by Django 5.0.1 on 2024-02-06 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfor',
            name='create_date',
        ),
        migrations.AlterField(
            model_name='userinfor',
            name='user_account',
            field=models.CharField(max_length=20, verbose_name='用户账号'),
        ),
        migrations.AlterField(
            model_name='userinfor',
            name='user_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='用户id'),
        ),
        migrations.AlterField(
            model_name='userinfor',
            name='user_name',
            field=models.CharField(max_length=20, verbose_name='用户名'),
        ),
        migrations.AlterField(
            model_name='userinfor',
            name='user_pwd',
            field=models.CharField(max_length=20, verbose_name='用户密码'),
        ),
    ]
