# Generated by Django 5.0.1 on 2024-03-05 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0003_userproject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproject',
            name='image_list',
            field=models.TextField(null=True, verbose_name='图片列表'),
        ),
    ]
